"""
Config Schema for Meshing-Around Web GUI
Auto-generated from settings.py analysis
"""

# Interface field template (reusable for all interfaces)
INTERFACE_FIELDS = {
    "enabled": {"type": "boolean", "default": False, "description": "Enable this interface"},
    "type": {"type": "enum", "options": ["serial", "tcp", "ble"], "default": "serial", "description": "Connection type"},
    "port": {"type": "string", "default": "/dev/ttyACM0", "description": "Serial port (for serial type)"},
    "hostname": {"type": "string", "default": "", "description": "IP:port for TCP connection (e.g., 192.168.1.251:4403)"},
    "mac": {"type": "string", "default": "", "description": "MAC address for BLE connection"},
}

# Primary interface has no 'enabled' field (always enabled)
PRIMARY_INTERFACE_FIELDS = {
    "type": {"type": "enum", "options": ["serial", "tcp", "ble"], "default": "serial", "description": "Connection type"},
    "port": {"type": "string", "default": "/dev/ttyACM0", "description": "Serial port (for serial type)"},
    "hostname": {"type": "string", "default": "", "description": "IP:port for TCP connection (e.g., 192.168.1.251:4403)"},
    "mac": {"type": "string", "default": "", "description": "MAC address for BLE connection"},
}

CONFIG_SCHEMA = {
    "general": {
        "title": "General Settings",
        "description": "Main bot behavior and feature toggles",
        "fields": {
            "respond_by_dm_only": {"type": "boolean", "default": True, "description": "Only respond via direct message"},
            "autoPingInChannel": {"type": "boolean", "default": False, "description": "Allow auto-ping in channels"},
            "defaultChannel": {"type": "integer", "default": 0, "description": "Default public channel number"},
            "ignoreDefaultChannel": {"type": "boolean", "default": False, "description": "Ignore the default channel"},
            "ignoreChannels": {"type": "list", "default": "", "description": "Comma-separated list of channels to ignore"},
            "cmdBang": {"type": "boolean", "default": False, "description": "Require ! prefix for commands"},
            "explicitCmd": {"type": "boolean", "default": True, "description": "Require explicit command words"},
            "favoriteNodeList": {"type": "list", "default": "", "description": "Comma-separated list of favorite node IDs"},
            "motd": {"type": "string", "default": "Thanks for using MeshBOT! Have a good day!", "description": "Message of the day"},
            "welcome_message": {"type": "string", "default": "MeshBot, here for you like a friend who is not.", "description": "Welcome message for new connections"},
            "whoami": {"type": "boolean", "default": True, "description": "Enable whoami command"},
            "DadJokes": {"type": "boolean", "default": True, "description": "Enable dad jokes module"},
            "DadJokesEmoji": {"type": "boolean", "default": False, "description": "Include emojis in jokes"},
            "spaceWeather": {"type": "boolean", "default": True, "description": "Enable space weather/solar module"},
            "rssEnable": {"type": "boolean", "default": True, "description": "Enable RSS feed module"},
            "rssFeedURL": {"type": "list", "default": "http://www.hackaday.com/rss.xml", "description": "Comma-separated RSS feed URLs"},
            "rssFeedNames": {"type": "list", "default": "default", "description": "Names for RSS feeds (match URL order)"},
            "rssMaxItems": {"type": "integer", "default": 3, "description": "Max RSS items to return"},
            "rssTruncate": {"type": "integer", "default": 100, "description": "Truncate RSS content to this many chars"},
            "enableNewsAPI": {"type": "boolean", "default": False, "description": "Enable NewsAPI.org integration"},
            "newsAPI_KEY": {"type": "string", "default": "", "description": "NewsAPI.org API key", "sensitive": True},
            "newsAPIregion": {"type": "string", "default": "us", "description": "NewsAPI region code"},
            "sort_by": {"type": "enum", "options": ["relevancy", "popularity", "publishedAt"], "default": "relevancy", "description": "News sort order"},
            "wikipedia": {"type": "boolean", "default": True, "description": "Enable Wikipedia search"},
            "useKiwixServer": {"type": "boolean", "default": False, "description": "Use local Kiwix instead of Wikipedia"},
            "kiwixURL": {"type": "string", "default": "http://127.0.0.1:8080", "description": "Kiwix server URL"},
            "kiwixLibraryName": {"type": "string", "default": "wikipedia_en_100_nopic_2025-09", "description": "Kiwix library name"},
            "ollama": {"type": "boolean", "default": False, "description": "Enable LLM integration (Ollama/OpenWebUI)"},
            "ollamaHostName": {"type": "string", "default": "http://localhost:11434", "description": "Ollama server URL"},
            "useOpenWebUI": {"type": "boolean", "default": False, "description": "Use OpenWebUI instead of direct Ollama"},
            "openWebUIURL": {"type": "string", "default": "http://localhost:3000", "description": "OpenWebUI API URL"},
            "openWebUIAPIKey": {"type": "string", "default": "", "description": "OpenWebUI API key", "sensitive": True},
            "ollamaModel": {"type": "string", "default": "gemma3:270m", "description": "LLM model name"},
            "rawLLMQuery": {"type": "boolean", "default": True, "description": "Send raw queries to LLM (no system prompt)"},
            "llmReplyToNonCommands": {"type": "boolean", "default": True, "description": "LLM replies to all DMs, not just ask: commands"},
            "llmUseWikiContext": {"type": "boolean", "default": False, "description": "Enable RAG with Wikipedia/Kiwix context"},
            "StoreForward": {"type": "boolean", "default": True, "description": "Enable store and forward"},
            "StoreLimit": {"type": "integer", "default": 3, "description": "Max messages to store/forward"},
            "reverseSF": {"type": "boolean", "default": False, "description": "Send oldest messages first"},
            "enableCmdHistory": {"type": "boolean", "default": True, "description": "Enable command history"},
            "lheardCmdIgnoreNodes": {"type": "list", "default": "", "description": "Nodes to ignore in lheard command"},
            "zuluTime": {"type": "boolean", "default": False, "description": "Use 24-hour time format"},
            "urlTimeout": {"type": "integer", "default": 15, "description": "URL request timeout in seconds"},
            "LogMessagesToFile": {"type": "boolean", "default": False, "description": "Log messages to file"},
            "SyslogToFile": {"type": "boolean", "default": True, "description": "Log system messages to file"},
            "sysloglevel": {"type": "enum", "options": ["DEBUG", "INFO", "WARNING", "ERROR", "CRITICAL"], "default": "DEBUG", "description": "Logging level"},
            "log_backup_count": {"type": "integer", "default": 32, "description": "Days of logs to keep"},
            "dont_retry_disconnect": {"type": "boolean", "default": False, "description": "Exit on disconnect instead of retrying"},
            "enableEcho": {"type": "boolean", "default": False, "description": "Enable echo command"},
            "echoChannel": {"type": "integer", "default": 9, "description": "Channel for echo command"},
        }
    },
    "emergencyHandler": {
        "title": "Emergency Handler",
        "description": "Emergency response and alert settings",
        "fields": {
            "enabled": {"type": "boolean", "default": False, "description": "Enable emergency handler"},
            "alert_channel": {"type": "integer", "default": 3, "description": "Channel to send emergency alerts"},
            "alert_interface": {"type": "integer", "default": 1, "description": "Interface for emergency alerts"},
        }
    },
    "sentry": {
        "title": "Sentry & Proximity Alerts",
        "description": "Detect nodes near your location and high-flying aircraft",
        "fields": {
            "SentryEnabled": {"type": "boolean", "default": False, "description": "Enable proximity detection"},
            "SentryInterface": {"type": "integer", "default": 1, "description": "Interface for sentry alerts"},
            "SentryChannel": {"type": "integer", "default": 5, "description": "Channel for sentry alerts"},
            "emailSentryAlerts": {"type": "boolean", "default": False, "description": "Email sentry alerts"},
            "detectionSensorAlert": {"type": "boolean", "default": False, "description": "Enable external GPIO sensor"},
            "sentryIgnoreList": {"type": "list", "default": "", "description": "Node IDs to ignore"},
            "sentryWatchList": {"type": "list", "default": "", "description": "Node IDs to specifically watch"},
            "SentryRadius": {"type": "integer", "default": 100, "description": "Detection radius in meters"},
            "SentryHoldoff": {"type": "integer", "default": 9, "description": "Holdoff multiplier (x20 seconds)"},
            "cmdShellSentryAlerts": {"type": "boolean", "default": False, "description": "Run shell command on alert"},
            "sentryAlertNear": {"type": "string", "default": "sentry_alert_near.sh", "description": "Shell script for near alert"},
            "sentryAlertAway": {"type": "string", "default": "sentry_alert_away.sh", "description": "Shell script for away alert"},
            "highFlyingAlert": {"type": "boolean", "default": True, "description": "Enable high-flying node detection"},
            "highFlyingAlertAltitude": {"type": "integer", "default": 2000, "description": "Altitude threshold in meters"},
            "highflyOpenskynetwork": {"type": "boolean", "default": True, "description": "Check OpenSkyNetwork for aircraft"},
            "highFlyingAlertInterface": {"type": "integer", "default": 1, "description": "Interface for high-fly alerts"},
            "highFlyingAlertChannel": {"type": "integer", "default": 2, "description": "Channel for high-fly alerts"},
            "highFlyingIgnoreList": {"type": "list", "default": "", "description": "Node IDs to ignore for high-fly"},
        }
    },
    "bbs": {
        "title": "BBS (Bulletin Board)",
        "description": "Bulletin board system for mesh messaging",
        "fields": {
            "enabled": {"type": "boolean", "default": False, "description": "Enable BBS"},
            "bbs_ban_list": {"type": "list", "default": "", "description": "Banned node IDs"},
            "bbs_admin_list": {"type": "list", "default": "", "description": "Admin node IDs"},
            "bbslink_enabled": {"type": "boolean", "default": False, "description": "Enable BBS sync between nodes"},
            "bbslink_whitelist": {"type": "list", "default": "", "description": "Whitelist for BBS sync"},
            "bbsAPI_enabled": {"type": "boolean", "default": False, "description": "Enable BBS API access"},
        }
    },
    "location": {
        "title": "Location & Weather",
        "description": "GPS location, weather, and alert services",
        "fields": {
            "enabled": {"type": "boolean", "default": True, "description": "Enable location module"},
            "lat": {"type": "float", "default": 48.50, "description": "Latitude coordinate"},
            "lon": {"type": "float", "default": -123.0, "description": "Longitude coordinate"},
            "fuzzConfigLocation": {"type": "boolean", "default": True, "description": "Fuzz (randomize) config location"},
            "fuzzItAll": {"type": "boolean", "default": False, "description": "Fuzz all location data"},
            "useMetric": {"type": "boolean", "default": False, "description": "Use metric units"},
            "repeaterLookup": {"type": "enum", "options": ["rbook", "artsci", "False"], "default": "rbook", "description": "Repeater lookup source"},
            "n2yoAPIKey": {"type": "string", "default": "", "description": "N2YO satellite API key", "sensitive": True},
            "satList": {"type": "list", "default": "25544,7530", "description": "NORAD satellite IDs to track"},
            "UseMeteoWxAPI": {"type": "boolean", "default": False, "description": "Use Open-Meteo instead of NOAA"},
            "NOAAforecastDuration": {"type": "integer", "default": 3, "description": "NOAA forecast days"},
            "NOAAalertCount": {"type": "integer", "default": 2, "description": "Number of weather alerts to show"},
            "wxAlertBroadcastEnabled": {"type": "boolean", "default": False, "description": "Enable NOAA weather alert broadcasts"},
            "ignoreEASenable": {"type": "boolean", "default": False, "description": "Enable EAS word filter"},
            "ignoreEASwords": {"type": "list", "default": "test,advisory", "description": "EAS words to ignore"},
            "enableExtraLocationWx": {"type": "boolean", "default": False, "description": "Add extra location to weather alerts"},
            "coastalEnabled": {"type": "boolean", "default": False, "description": "Enable coastal weather forecasts"},
            "myCoastalZone": {"type": "string", "default": "", "description": "NOAA coastal zone URL"},
            "coastalForecastDays": {"type": "integer", "default": 3, "description": "Coastal forecast days"},
            "riverList": {"type": "list", "default": "", "description": "USGS river station IDs"},
            "ipawsAlertEnabled": {"type": "boolean", "default": False, "description": "Enable FEMA IPAWS alerts"},
            "myFIPSList": {"type": "list", "default": "", "description": "FIPS codes for local alerts"},
            "mySAMEList": {"type": "list", "default": "", "description": "SAME codes for local alerts"},
            "ignoreFEMAenable": {"type": "boolean", "default": True, "description": "Enable FEMA word filter"},
            "ignoreFEMAwords": {"type": "list", "default": "test,exercise", "description": "FEMA words to ignore"},
            "volcanoAlertBroadcastEnabled": {"type": "boolean", "default": False, "description": "Enable USGS volcano alerts"},
            "ignoreUSGSEnable": {"type": "boolean", "default": False, "description": "Enable USGS word filter"},
            "ignoreUSGSWords": {"type": "list", "default": "test,advisory", "description": "USGS words to ignore"},
            "enableDEalerts": {"type": "boolean", "default": False, "description": "Enable Germany/DE alerts"},
            "myRegionalKeysDE": {"type": "list", "default": "", "description": "German regional codes"},
            "eAlertBroadcastCh": {"type": "list", "default": "3", "description": "Channel(s) for emergency broadcasts"},
        }
    },
    "checklist": {
        "title": "Checklist System",
        "description": "Check-in/check-out tracking system",
        "fields": {
            "enabled": {"type": "boolean", "default": False, "description": "Enable checklist"},
            "checklist_db": {"type": "string", "default": "data/checklist.db", "description": "Database file path"},
            "reverse_in_out": {"type": "boolean", "default": False, "description": "Reverse in/out logic"},
            "auto_approve": {"type": "boolean", "default": True, "description": "Auto-approve new checklists"},
        }
    },
    "inventory": {
        "title": "Inventory & POS",
        "description": "Inventory management and point of sale",
        "fields": {
            "enabled": {"type": "boolean", "default": False, "description": "Enable inventory system"},
            "inventory_db": {"type": "string", "default": "data/inventory.db", "description": "Database file path"},
            "disable_penny": {"type": "boolean", "default": False, "description": "Round to nickels (no pennies)"},
        }
    },
    "qrz": {
        "title": "QRZ Hello",
        "description": "Greet new nodes with ham radio callsigns",
        "fields": {
            "enabled": {"type": "boolean", "default": False, "description": "Enable QRZ hello"},
            "qrz_db": {"type": "string", "default": "data/qrz.db", "description": "Database file path"},
            "qrz_hello_string": {"type": "string", "default": "MeshBot says Hello! DM for more info.", "description": "Hello message"},
            "training": {"type": "boolean", "default": True, "description": "Training mode (don't send messages)"},
        }
    },
    "repeater": {
        "title": "Repeater Mode",
        "description": "Rebroadcast messages between interfaces",
        "fields": {
            "enabled": {"type": "boolean", "default": False, "description": "Enable repeater mode"},
            "repeater_channels": {"type": "list", "default": "", "description": "Channels to repeat (e.g., 2,3)"},
        }
    },
    "scheduler": {
        "title": "Scheduler",
        "description": "Scheduled automatic messages",
        "fields": {
            "enabled": {"type": "boolean", "default": False, "description": "Enable scheduler"},
            "useCustomScheduler": {"type": "boolean", "default": False, "description": "Use custom schedules (from Schedules page)", "controls": "value"},
            "interface": {"type": "integer", "default": 1, "description": "Interface for scheduled messages"},
            "channel": {"type": "integer", "default": 2, "description": "Channel for scheduled messages"},
            "message": {"type": "string", "default": "MeshBot says Hello!", "description": "Scheduled message text"},
            "schedulerMotd": {"type": "boolean", "default": False, "description": "Use MOTD as scheduled message"},
            "value": {"type": "string", "default": "", "description": "Schedule type (min,hour,day,mon-sun,joke,weather,etc)"},
            "interval": {"type": "string", "default": "", "description": "Interval (e.g., every 2 days)"},
            "time": {"type": "string", "default": "", "description": "Time in 24:00 format"},
        }
    },
    "radioMon": {
        "title": "Radio Monitoring",
        "description": "Monitor radios via hamlib, VOX, WSJT-X, JS8Call",
        "fields": {
            "dxspotter_enabled": {"type": "boolean", "default": True, "description": "Enable DX cluster command"},
            "sigWatchBroadcastInterface": {"type": "integer", "default": 1, "description": "Interface for signal alerts"},
            "sigWatchBroadcastCh": {"type": "list", "default": "2", "description": "Channel(s) for signal alerts"},
            "enabled": {"type": "boolean", "default": False, "description": "Enable hamlib rig control"},
            "rigControlServerAddress": {"type": "string", "default": "127.0.0.1:4532", "description": "Hamlib rigctld address"},
            "signalDetectionThreshold": {"type": "integer", "default": -10, "description": "Min SNR for detection (dB)"},
            "signalHoldTime": {"type": "integer", "default": 10, "description": "Signal hold time (seconds)"},
            "signalCooldown": {"type": "integer", "default": 5, "description": "Cooldown between alerts"},
            "signalCycleLimit": {"type": "integer", "default": 5, "description": "Cycle limit for reset"},
            "voxDetectionEnabled": {"type": "boolean", "default": False, "description": "Enable VOX audio detection"},
            "voxDescription": {"type": "string", "default": "VOX", "description": "VOX alert description"},
            "useLocalVoxModel": {"type": "boolean", "default": False, "description": "Use local speech model"},
            "voxLanguage": {"type": "string", "default": "en-us", "description": "VOX language"},
            "voxInputDevice": {"type": "string", "default": "default", "description": "Audio input device"},
            "voxOnTrapList": {"type": "boolean", "default": True, "description": "Enable VOX trap words"},
            "voxTrapList": {"type": "list", "default": "chirpy", "description": "VOX trigger words"},
            "voxEnableCmd": {"type": "boolean", "default": True, "description": "Allow weather/joke via VOX"},
            "meshagesTTS": {"type": "boolean", "default": False, "description": "Text-to-speech for messages"},
            "ttsChannels": {"type": "list", "default": "2", "description": "Channels for TTS"},
            "wsjtxDetectionEnabled": {"type": "boolean", "default": False, "description": "Enable WSJT-X monitoring"},
            "wsjtxUdpServerAddress": {"type": "string", "default": "127.0.0.1:2237", "description": "WSJT-X UDP address"},
            "wsjtxWatchedCallsigns": {"type": "list", "default": "", "description": "Callsigns to watch"},
            "js8callDetectionEnabled": {"type": "boolean", "default": False, "description": "Enable JS8Call monitoring"},
            "js8callServerAddress": {"type": "string", "default": "127.0.0.1:2442", "description": "JS8Call TCP address"},
            "js8callWatchedCallsigns": {"type": "list", "default": "", "description": "Callsigns to watch"},
        }
    },
    "fileMon": {
        "title": "File Monitoring",
        "description": "Monitor files for changes and news broadcasts",
        "fields": {
            "filemon_enabled": {"type": "boolean", "default": False, "description": "Enable file monitoring"},
            "file_path": {"type": "string", "default": "alert.txt", "description": "File to monitor"},
            "broadcastCh": {"type": "list", "default": "2", "description": "Broadcast channel(s)"},
            "enable_read_news": {"type": "boolean", "default": False, "description": "Enable news command"},
            "news_file_path": {"type": "string", "default": "../data/news.txt", "description": "News file path"},
            "news_random_line": {"type": "boolean", "default": False, "description": "Return random line"},
            "news_block_mode": {"type": "boolean", "default": True, "description": "Return random block"},
            "enable_runShellCmd": {"type": "boolean", "default": False, "description": "Enable shell commands"},
            "allowXcmd": {"type": "boolean", "default": False, "description": "Allow x: direct shell command"},
            "twoFactor_enabled": {"type": "boolean", "default": True, "description": "Require 2FA for x: commands"},
            "twoFactor_timeout": {"type": "integer", "default": 100, "description": "2FA timeout (seconds)"},
        }
    },
    "smtp": {
        "title": "Email Settings",
        "description": "SMTP and IMAP email configuration",
        "fields": {
            "enableSMTP": {"type": "boolean", "default": False, "description": "Enable outgoing email"},
            "enableImap": {"type": "boolean", "default": False, "description": "Enable incoming email"},
            "sysopEmails": {"type": "list", "default": "", "description": "Sysop email addresses"},
            "SMTP_SERVER": {"type": "string", "default": "smtp.gmail.com", "description": "SMTP server"},
            "SMTP_PORT": {"type": "integer", "default": 587, "description": "SMTP port"},
            "FROM_EMAIL": {"type": "string", "default": "", "description": "From email address"},
            "SMTP_AUTH": {"type": "boolean", "default": True, "description": "Require SMTP auth"},
            "SMTP_USERNAME": {"type": "string", "default": "", "description": "SMTP username"},
            "SMTP_PASSWORD": {"type": "string", "default": "", "description": "SMTP password", "sensitive": True},
            "EMAIL_SUBJECT": {"type": "string", "default": "Meshtastic", "description": "Email subject prefix"},
            "IMAP_SERVER": {"type": "string", "default": "imap.gmail.com", "description": "IMAP server"},
            "IMAP_PORT": {"type": "integer", "default": 993, "description": "IMAP port"},
            "IMAP_USERNAME": {"type": "string", "default": "", "description": "IMAP username"},
            "IMAP_PASSWORD": {"type": "string", "default": "", "description": "IMAP password", "sensitive": True},
            "IMAP_FOLDER": {"type": "string", "default": "inbox", "description": "IMAP folder"},
        }
    },
    "games": {
        "title": "Games",
        "description": "Enable/disable game modules",
        "fields": {
            "game_hop_limit": {"type": "integer", "default": 5, "description": "Max hops for game messages"},
            "disable_emojis": {"type": "boolean", "default": False, "description": "Disable emojis in games"},
            "dopeWars": {"type": "boolean", "default": True, "description": "Enable DopeWars game"},
            "lemonade": {"type": "boolean", "default": True, "description": "Enable Lemonade Stand"},
            "blackjack": {"type": "boolean", "default": True, "description": "Enable Blackjack"},
            "videopoker": {"type": "boolean", "default": True, "description": "Enable Video Poker"},
            "mastermind": {"type": "boolean", "default": True, "description": "Enable Mastermind"},
            "golfsim": {"type": "boolean", "default": True, "description": "Enable Golf Simulator"},
            "hangman": {"type": "boolean", "default": True, "description": "Enable Hangman"},
            "hamtest": {"type": "boolean", "default": True, "description": "Enable Ham Radio Test"},
            "tictactoe": {"type": "boolean", "default": True, "description": "Enable Tic-Tac-Toe"},
            "wordOfTheDay": {"type": "boolean", "default": True, "description": "Enable Word of the Day"},
            "battleShip": {"type": "boolean", "default": True, "description": "Enable Battleship"},
            "quiz": {"type": "boolean", "default": False, "description": "Enable Quiz game"},
            "survey": {"type": "boolean", "default": False, "description": "Enable Survey system"},
            "defaultSurvey": {"type": "string", "default": "example", "description": "Default survey name"},
            "surveyRecordID": {"type": "boolean", "default": True, "description": "Record user ID in surveys"},
            "surveyRecordLocation": {"type": "boolean", "default": True, "description": "Record location in surveys"},
        }
    },
    "messagingSettings": {
        "title": "Messaging Settings",
        "description": "Message timing, chunking, and debugging",
        "fields": {
            "responseDelay": {"type": "float", "default": 2.2, "description": "Delay between responses (seconds)"},
            "splitDelay": {"type": "float", "default": 2.5, "description": "Delay between message chunks"},
            "MESSAGE_CHUNK_SIZE": {"type": "integer", "default": 160, "description": "Max message chunk size (chars)"},
            "wantAck": {"type": "boolean", "default": False, "description": "Request message acknowledgement"},
            "maxBuffer": {"type": "integer", "default": 200, "description": "Max buffer size (bytes)"},
            "enableHopLogs": {"type": "boolean", "default": False, "description": "Log hop count data"},
            "noisyNodeLogging": {"type": "boolean", "default": False, "description": "Log noisy node telemetry"},
            "noisyTelemetryLimit": {"type": "integer", "default": 5, "description": "Noisy node packet threshold"},
            "logMetaStats": {"type": "boolean", "default": True, "description": "Log metadata statistics"},
            "DEBUGpacket": {"type": "boolean", "default": False, "description": "Detailed packet logging"},
            "debugMetadata": {"type": "boolean", "default": False, "description": "Debug metadata logging"},
            "metadataFilter": {"type": "list", "default": "TELEMETRY_APP,POSITION_APP", "description": "Metadata filter ports"},
            "autoBanEnabled": {"type": "boolean", "default": False, "description": "Enable automatic node banning"},
            "autoBanThreshold": {"type": "integer", "default": 5, "description": "Offenses before auto-ban"},
            "apiThrottleValue": {"type": "integer", "default": 20, "description": "API throttle limit"},
            "autoBanTimeframe": {"type": "integer", "default": 3600, "description": "Ban timeframe (seconds)"},
        }
    },
}

# Section display order (interfaces handled separately)
SECTION_ORDER = [
    "general", "emergencyHandler", "sentry",
    "location", "bbs", "checklist", "inventory", "qrz", "repeater",
    "scheduler", "radioMon", "fileMon", "smtp", "games", "messagingSettings"
]
